### ISSUE TITLE
Hvis man er i gang med at tilføje ny genstand og vil tilbage nulstiller den ikke

### ISSUE THREAD

**Issue by Tekrus** [techkrus/FutureManagement#235]
![image](https://user-images.githubusercontent.com/21969475/52522229-9fce9f80-2c82-11e9-8700-5a1d678af5ee.png)

Ved tryk på "Tilføj ny genstand" i menuen redirecter den ikke

**Comment by jenspetur94** [comment]
Er du sikker på at den her nogensinde blev fikset siden at du lukker den ? @Tekrus

**Comment by Tekrus** [comment]
@jenspetur94 Jeg er ikke sikker, men det har ikke været rapporteret som en bug i noget tid! (og jeg var ved at rydde op i alle åbne issues jeg havde på github)
